"""add_curriculum_classes

Revision ID: 037674da56d5
Revises: 5ee9eba011df
Create Date: 2026-02-21 17:31:46.300653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037674da56d5'
down_revision = '5ee9eba011df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
