"""Add StudentTrash model

Revision ID: 5ee9eba011df
Revises: f6a7b8c9d0e1
Create Date: 2026-02-21 16:57:52.092957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee9eba011df'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_trash',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_trash_expires_at'), 'student_trash', ['expires_at'], unique=False)
    op.create_index(op.f('ix_student_trash_id'), 'student_trash', ['id'], unique=False)
    op.create_index(op.f('ix_student_trash_user_id'), 'student_trash', ['user_id'], unique=True)
    op.add_column('curriculums', sa.Column('school_id', sa.UUID(), nullable=False))
    op.drop_index('ix_curriculums_class_id', table_name='curriculums')
    op.create_index(op.f('ix_curriculums_school_id'), 'curriculums', ['school_id'], unique=False)
    op.drop_constraint('curriculums_class_id_fkey', 'curriculums', type_='foreignkey')
    op.create_foreign_key(None, 'curriculums', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_column('curriculums', 'class_id')
    op.drop_index('ix_users_school_student_number', table_name='users', postgresql_where='(student_number IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_school_student_number', 'users', ['school_id', 'student_number'], unique=True, postgresql_where='(student_number IS NOT NULL)')
    op.add_column('curriculums', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('curriculums_school_id_fkey', 'curriculums', type_='foreignkey')
    op.create_foreign_key('curriculums_class_id_fkey', 'curriculums', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_curriculums_school_id'), table_name='curriculums')
    op.create_index('ix_curriculums_class_id', 'curriculums', ['class_id'], unique=False)
    op.drop_column('curriculums', 'school_id')
    op.drop_index(op.f('ix_student_trash_user_id'), table_name='student_trash')
    op.drop_index(op.f('ix_student_trash_id'), table_name='student_trash')
    op.drop_index(op.f('ix_student_trash_expires_at'), table_name='student_trash')
    op.drop_table('student_trash')
    # ### end Alembic commands ###
