"""add_topic

Revision ID: 7f081ab2c64e
Revises: e4304bb55836
Create Date: 2026-02-21 17:49:17.803900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f081ab2c64e'
down_revision = 'e4304bb55836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('curriculum_id', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('curriculums.id', ondelete='CASCADE'), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('duration_hours', sa.Float(), nullable=True),
        sa.Column('learning_objectives', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False)
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_curriculum_id'), 'topics', ['curriculum_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_curriculum_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
