"""add_topic

Revision ID: 7f081ab2c64e
Revises: e4304bb55836
Create Date: 2026-02-21 17:49:17.803900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f081ab2c64e'
down_revision = 'e4304bb55836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
