"""add_topics_and_rubric_to_assignment

Revision ID: 84d9cb7499cd
Revises: 574b256045e7
Create Date: 2026-03-05 12:28:50.764355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d9cb7499cd'
down_revision = '574b256045e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs', if_exists=True)
    op.add_column('assignments', sa.Column('topics', sa.JSON(), nullable=True))
    op.add_column('assignments', sa.Column('rubric_url', sa.String(length=512), nullable=True))
    op.add_column('assignments', sa.Column('rubric_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_assignments_category'), 'assignments', ['category'], unique=False)
    # Ensure enum values match Python models (uppercase) and preserve lowercase for compatibility if needed
    op.execute("ALTER TYPE question_type ADD VALUE IF NOT EXISTS 'TRUE_FALSE'")
    op.execute("ALTER TYPE question_type ADD VALUE IF NOT EXISTS 'true_false'")
    op.execute("ALTER TYPE task_category ADD VALUE IF NOT EXISTS 'ASSESSMENT'")
    op.execute("ALTER TYPE task_category ADD VALUE IF NOT EXISTS 'ASSIGNMENT'")
    op.drop_index('ix_users_school_student_number', table_name='users', postgresql_where='(student_number IS NOT NULL)', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_school_student_number', 'users', ['school_id', 'student_number'], unique=True, postgresql_where='(student_number IS NOT NULL)')
    op.drop_index(op.f('ix_assignments_category'), table_name='assignments')
    op.drop_column('assignments', 'rubric_data')
    op.drop_column('assignments', 'rubric_url')
    op.drop_column('assignments', 'topics')
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
