"""add_curriculum_classes

Revision ID: e4304bb55836
Revises: 5ee9eba011df
Create Date: 2026-02-21 17:40:38.155345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4304bb55836'
down_revision = '5ee9eba011df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_classes',
        sa.Column('curriculum_id', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('curriculums.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('class_id', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('classes.id', ondelete='CASCADE'), primary_key=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curriculum_classes')
    # ### end Alembic commands ###
