"""Teacher Access Code Model for Invitation System"""

from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.models.base import BaseModel, SchoolScopedMixin


class TeacherAccessCode(BaseModel, SchoolScopedMixin):
    """
    Access codes for teacher registration.
    Generated by school admins to invite teachers.
    """
    __tablename__ = "teacher_access_codes"
    
    code = Column(String(50), unique=True, nullable=False, index=True)
    is_used = Column(Boolean, default=False, nullable=False, index=True)
    expires_at = Column(DateTime, nullable=True)
    
    # Foreign Keys
    created_by_admin_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    invited_teacher_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True)
    used_by_teacher_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    
    # Relationships
    school = relationship("School")
    created_by_admin = relationship("User", foreign_keys=[created_by_admin_id])
    used_by_teacher = relationship("User", foreign_keys=[used_by_teacher_id])
    
    def __repr__(self) -> str:
        return f"<TeacherAccessCode {self.code} - {'Used' if self.is_used else 'Available'}>"
